In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('dist_matrix0.csv',header=0, index_col=0)

In [3]:
df

,1,2,3,4,5,6,7,8,9,10,...,31,32,33,34,35,36,37,38,39,40
1,999.00,11.03,8.65,9.12,11.25,3.82,14.30,4.17,6.39,15.46,...,4.20,3.92,23.70,19.22,13.21,1.08,20.77,6.00,3.18,5.11
2,11.03,999.00,8.77,5.35,5.95,10.24,3.87,8.86,4.77,6.32,...,11.07,11.22,18.91,8.30,4.06,10.35,16.85,7.59,9.26,7.06
3,8.65,8.77,999.00,3.47,13.22,5.12,9.72,4.49,7.64,9.23,...,11.83,11.71,15.05,16.15,12.72,8.90,12.14,2.95,5.47,9.32
4,9.12,5.35,3.47,999.00,10.31,6.62,6.44,5.39,5.50,6.60,...,11.17,11.16,15.69,12.75,9.36,8.95,13.11,3.48,6.23,7.78
5,11.25,5.95,13.22,10.31,999.00,12.44,9.29,11.28,5.95,12.08,...,9.04,9.34,24.86,10.29,3.67,10.22,22.74,10.98,11.15,6.14
6,3.82,10.24,5.12,6.62,12.44,999.00,12.74,1.39,6.59,13.23,...,7.70,7.48,20.08,18.50,13.39,4.41,17.09,3.14,1.32,6.78
7,14.30,3.87,9.72,6.44,9.29,12.74,999.00,11.38,8.40,2.93,...,14.83,14.96,16.19,6.53,6.24,13.76,14.57,9.69,12.01,10.83
8,4.17,8.86,4.49,5.39,11.28,1.39,11.38,999.00,5.36,11.97,...,7.53,7.37,19.54,17.11,12.06,4.44,16.62,1.95,0.99,5.91
9,6.39,4.77,7.64,5.50,5.95,6.59,8.40,5.36,999.00,10.23,...,6.47,6.57,21.14,12.83,6.96,5.62,18.61,5.11,5.35,2.53
10,15.46,6.32,9.23,6.60,12.08,13.23,2.93,11.97,10.23,999.00,...,16.67,16.75,13.28,8.43,9.16,15.10,11.78,10.09,12.77,12.75
11,18.85,7.82,14.95,11.66,10.96,17.76,5.24,16.38,12.56,6.69,...,18.59,18.79,18.83,1.98,7.29,18.17,17.93,14.81,16.92,14.66
12,14.70,4.67,13.42,9.97,5.30,14.61,5.67,13.25,8.36,8.57,...,13.59,13.83,21.85,5.04,1.70,13.84,20.23,12.17,13.51,9.91
13,10.98,6.58,13.49,10.71,0.79,12.41,10.01,11.30,6.04,12.78,...,8.53,8.84,25.46,11.06,4.46,9.93,23.29,11.14,11.10,5.91
14,9.82,5.74,12.20,9.50,1.43,11.10,9.39,9.98,4.72,12.04,...,7.69,7.98,24.48,11.24,4.51,8.79,22.24,9.82,9.80,4.71
15,17.72,6.76,13.45,10.20,10.65,16.43,3.76,15.06,11.53,5.13,...,17.74,17.91,17.58,3.34,7.02,17.09,16.54,13.43,15.64,13.76
16,6.46,7.36,2.64,3.04,10.98,3.58,9.32,2.42,5.18,9.65,...,9.27,9.18,17.42,15.38,11.02,6.52,14.59,0.47,3.35,6.69
17,7.88,4.15,9.24,6.66,4.11,8.44,8.02,7.22,1.86,10.26,...,7.04,7.23,22.02,11.60,5.33,6.99,19.63,6.88,7.18,3.12
18,12.64,5.65,13.71,10.57,1.67,13.50,8.48,12.26,6.91,11.37,...,10.66,10.94,24.43,8.72,2.37,11.64,22.47,11.73,12.24,7.54
19,3.64,10.67,5.51,7.09,12.73,0.47,13.19,1.83,6.93,13.69,...,7.64,7.41,20.41,18.94,13.77,4.33,17.41,3.60,1.58,6.98
20,1.92,10.12,6.75,7.48,11.35,1.97,13.08,2.29,5.84,13.98,...,5.75,5.52,21.80,18.41,12.80,2.45,18.85,4.19,1.31,5.36
21,17.45,10.34,9.53,8.41,16.27,14.45,7.40,13.46,13.37,4.50,...,19.51,19.52,8.79,12.47,13.59,17.35,7.41,11.51,14.40,15.86
22,19.29,27.95,19.91,23.20,30.24,17.97,29.61,19.29,24.54,28.98,...,22.96,22.61,28.13,35.93,31.35,20.37,25.35,20.36,19.19,24.21
23,11.15,0.27,8.65,5.21,6.22,10.27,3.63,8.88,4.94,6.05,...,11.27,11.42,18.65,8.24,4.24,10.49,16.60,7.57,9.32,7.26
24,20.31,17.41,11.79,13.24,23.21,16.55,15.48,16.22,18.71,12.81,...,23.62,23.50,4.45,21.07,21.23,20.66,1.83,14.72,17.18,20.82
25,12.58,4.35,6.86,3.85,10.30,10.44,2.97,9.16,7.52,2.87,...,13.90,13.96,14.56,9.50,8.04,12.23,12.54,7.31,9.93,10.05
26,3.55,12.29,11.94,11.76,10.66,7.35,15.96,7.48,7.56,17.61,...,1.66,1.33,26.94,19.96,13.44,3.04,24.07,9.10,6.53,5.29
27,11.78,2.11,10.72,7.37,4.24,11.61,5.05,10.25,5.40,7.85,...,11.05,11.25,20.81,7.53,2.00,10.96,18.85,9.25,10.50,7.18
28,7.20,10.06,2.18,5.13,13.76,3.42,11.56,3.32,7.88,11.32,...,10.83,10.66,16.71,17.86,13.82,7.66,13.70,2.78,4.18,9.02
29,5.49,12.51,13.46,12.84,9.86,9.18,16.32,9.12,8.02,18.25,...,1.67,1.76,28.32,19.70,13.01,4.76,25.52,10.55,8.22,5.51
30,20.54,16.41,11.89,12.75,22.31,16.89,14.09,16.38,18.25,11.29,...,23.57,23.48,3.21,19.35,20.06,20.78,0.52,14.71,17.36,20.50
31,4.20,11.07,11.83,11.17,9.04,7.70,14.83,7.53,6.47,16.67,...,999.00,0.35,26.65,18.52,11.92,3.31,23.86,8.90,6.67,4.01
32,3.92,11.22,11.71,11.16,9.34,7.48,14.96,7.37,6.57,16.75,...,0.35,999.00,26.58,18.74,12.17,3.08,23.77,8.79,6.48,4.16
33,23.70,18.91,15.05,15.69,24.86,20.08,16.19,19.54,21.14,13.28,...,26.65,26.58,999.00,20.81,22.35,23.92,3.10,17.84,20.52,23.47
34,19.22,8.30,16.15,12.75,10.29,18.50,6.53,17.11,12.83,8.43,...,18.52,18.74,20.81,999.00,6.73,18.45,19.86,15.68,17.56,14.71
35,13.21,4.06,12.72,9.36,3.67,13.39,6.24,12.06,6.96,9.16,...,11.92,12.17,22.35,6.73,999.00,12.31,20.53,11.17,12.23,8.32
36,1.08,10.35,8.90,8.95,10.22,4.41,13.76,4.44,5.62,15.10,...,3.31,3.08,23.92,18.45,12.31,999.00,21.04,6.09,3.50,4.10
37,20.77,16.85,12.14,13.11,22.74,17.09,14.57,16.62,18.61,11.78,...,23.86,23.77,3.10,19.86,20.53,21.04,999.00,14.99,17.60,20.84
38,6.00,7.59,2.95,3.48,10.98,3.14,9.69,1.95,5.11,10.09,...,8.90,8.79,17.84,15.68,11.17,6.09,14.99,999.00,2.89,6.46
39,3.18,9.26,5.47,6.23,11.15,1.32,12.01,0.99,5.35,12.77,...,6.67,6.48,20.52,17.56,12.23,3.50,17.60,2.89,999.00,5.47
40,5.11,7.06,9.32,7.78,6.14,6.78,10.83,5.91,2.53,12.75,...,4.01,4.16,23.47,14.71,8.32,4.10,20.84,6.46,5.47,999.00

In [4]:
columns = [1,2,5,6,7,8,11,12,13,14,15,16,17,'base',19,20,22,23,24,25,26,27,28,29,30,31]
df.columns = columns

ValueError: Length mismatch: Expected axis has 40 elements, new values have 26 elements

In [5]:
df.index = columns

In [6]:
df = df / 1000

In [7]:
d=[0.4,0.52,0.56,0.19,0.28,0.6,0.67,0.47,0.97,0.34,0.98,0.64,0.11,0,0.92,0.38,0.82,0.53,0.64,0.05,0.75,0.28,0.64,0.54,0.76,0.4]
d = pd.DataFrame(d, index=columns, columns=['Demanda'])
d

      Demanda
1        0.40
2        0.52
5        0.56
6        0.19
7        0.28
8        0.60
11       0.67
12       0.47
13       0.97
14       0.34
15       0.98
16       0.64
17       0.11
base     0.00
19       0.92
20       0.38
22       0.82
23       0.53
24       0.64
25       0.05
26       0.75
27       0.28
28       0.64
29       0.54
30       0.76
31       0.40

In [8]:
v = 20

In [9]:
demandas = d.copy()

In [10]:
demandas = d.copy()
n0 = 'base'
ruta = [n0]
rutas = []
costos = []
while demandas.sum()["Demanda"] > 0:
    carga = 1
    ruta = [n0]
    costo = 1
    while carga > 0 and demandas["Demanda"].sum() > 0:
        n = df.loc[n0, np.array(demandas["Demanda"]>0)].idxmax()
        ruta.append(n)
        
        if carga > demandas.loc[n].Demanda:
            carga -= demandas.loc[n].Demanda
            demandas.loc[n].Demanda = 0
            costo += df.loc[ruta[-2],n]/v
            
        elif carga == demandas.loc[n].Demanda:
            carga = 0
            demandas.loc[n].Demanda = 0
            ruta.append(n0)
            costo += df.loc[ruta[-2],n0]/v
            
        else:
            demandas.loc[n].Demanda -= carga
            carga = 0
            ruta.append(n0)
            costo += df.loc[ruta[-2],n0]/v
            
        while carga > 0 and demandas["Demanda"].sum() > 0:
            if df.loc[df.loc[n, np.array(demandas["Demanda"]>0)].idxmin(),n] < df.loc[n,'base']:
                n = df.loc[n, np.array(demandas["Demanda"]>0)].idxmin()

                ruta.append(n)
                
                if carga > demandas.loc[n].Demanda:
                    carga -= demandas.loc[n].Demanda
                    demandas.loc[n].Demanda = 0
                    costo += df.loc[ruta[-2],n]/v
                    
                elif carga == demandas.loc[n].Demanda:
                    carga = 0
                    demandas.loc[n].Demanda = 0
                    ruta.append(n0)
                    costo += df.loc[ruta[-2],n0]/v
                    
                else:
                    demandas.loc[n].Demanda -= carga
                    carga = 0
                    ruta.append(n0)
                    costo += df.loc[ruta[-2],n0]/v
                    
            else:
                carga = 0
                ruta.append(n0)
                costo += df.loc[ruta[-2],n0]/v
            
        
    rutas.append(ruta)
    costos.append(costo)
if rutas[-1][-1] != n0:
    rutas[-1].append(n0)
    costo += df.loc[ruta[-2],n0]
    
    
rutas

[['base', 1, 5, 11, 'base'],
 ['base', 6, 2, 8, 'base'],
 ['base', 7, 8, 14, 15, 'base'],
 ['base', 26, 25, 19, 'base'],
 ['base', 27, 28, 29, 'base'],
 ['base', 20, 22, 'base'],
 ['base', 13, 22, 'base'],
 ['base', 29, 30, 'base'],
 ['base', 11, 12, 'base'],
 ['base', 19, 16, 'base'],
 ['base', 22, 23, 24, 'base'],
 ['base', 12, 31, 15, 'base'],
 ['base', 30, 24, 'base'],
 ['base', 16, 17, 'base'],
 ['base', 15, 'base']]

In [11]:
parte_decimal_horas = 0
for i in range(len(costos)):
    parte_decimal_horas += costos[i]
parte_decimal_horas

15.00110944814618

# Parte Entera

Nodos 3,4,9,10,21

In [12]:
distances_enteras = pd.read_csv('distances.csv',header=0,index_col=0)

In [13]:
distances_enteras = distances_enteras / 1000
distances_enteras

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
1,0.000000,0.626132,0.441787,0.318619,0.277378,0.868966,1.013380,0.874584,0.766652,0.700437,...,1.506787,1.510845,1.464129,1.791419,2.065509,1.993305,1.939598,1.856978,1.745490,0.975203
2,0.626132,0.000000,0.209060,0.386095,0.614452,0.242857,0.428809,0.400255,0.453782,0.575876,...,1.114286,1.204922,1.242529,1.923114,2.205466,1.535565,1.513275,1.485714,1.446742,0.939931
3,0.441787,0.209060,0.000000,0.177166,0.405714,0.441971,0.572349,0.457580,0.414325,0.462548,...,1.147683,1.200014,1.203427,1.782280,2.065072,1.606731,1.568436,1.514431,1.442996,0.823774
4,0.318619,0.386095,0.177166,0.000000,0.228589,0.614226,0.714834,0.558540,0.450994,0.418120,...,1.195369,1.215012,1.188915,1.666724,1.948398,1.676880,1.626279,1.551565,1.454230,0.748419
5,0.277378,0.614452,0.405714,0.228589,0.000000,0.838487,0.913951,0.729131,0.575876,0.460035,...,1.284920,1.264911,1.202463,1.529572,1.807016,1.783828,1.719338,1.620909,1.493523,0.700583
6,0.868966,0.242857,0.441971,0.614226,0.838487,0.000000,0.257143,0.365893,0.515079,0.690460,...,1.022702,1.153964,1.229900,2.021164,2.300177,1.390419,1.385788,1.388069,1.386892,1.030158
7,1.013380,0.428809,0.572349,0.714834,0.913951,0.257143,0.000000,0.230350,0.429523,0.629220,...,0.773146,0.920182,1.017400,1.885768,2.158467,1.134343,1.128662,1.134703,1.146156,0.912945
8,0.874584,0.400255,0.457580,0.558540,0.729131,0.365893,0.230350,0.000000,0.200000,0.400000,...,0.714429,0.810769,0.868966,1.673381,1.949411,1.152194,1.120678,1.085808,1.050656,0.690460
9,0.766652,0.453782,0.414325,0.450994,0.575876,0.515079,0.429523,0.200000,0.000000,0.200000,...,0.745736,0.785714,0.796933,1.506246,1.785714,1.226660,1.175429,1.106659,1.028671,0.515079
10,0.700437,0.575876,0.462548,0.418120,0.460035,0.690460,0.629220,0.400000,0.200000,0.000000,...,0.825734,0.810769,0.771429,1.348090,1.630137,1.327342,1.259900,1.162071,1.045203,0.365893
11,0.688091,0.733040,0.579859,0.475661,0.414286,0.876449,0.829064,0.600000,0.400000,0.200000,...,0.942099,0.881673,0.796933,1.202463,1.485233,1.448786,1.368598,1.247446,1.098515,0.287139
12,0.859521,0.955008,0.802186,0.688186,0.582920,1.087968,1.014587,0.784545,0.589015,0.397954,...,0.971534,0.860114,0.730110,0.981149,1.263700,1.468930,1.373956,1.227325,1.046374,0.202031
13,1.292048,0.793468,0.879095,0.973846,1.121315,0.657764,0.401019,0.421852,0.545856,0.705662,...,0.389924,0.575876,0.721110,1.703598,1.957977,0.742445,0.728711,0.738034,0.776833,0.832993
14,1.088811,0.769309,0.757191,0.782362,0.863075,0.752818,0.556410,0.389924,0.343155,0.404313,...,0.421852,0.443087,0.479157,1.350586,1.616370,0.923392,0.856309,0.769309,0.686309,0.446529
15,1.052596,0.863075,0.798386,0.774813,0.796933,0.899093,0.737481,0.536238,0.409330,0.357143,...,0.546977,0.472941,0.414286,1.149978,1.421123,1.050559,0.963942,0.838122,0.696639,0.239472
16,1.260081,1.355506,1.215428,1.106013,0.988179,1.461299,1.343969,1.123355,0.946685,0.781344,...,1.054286,0.868783,0.678690,0.567997,0.850743,1.490873,1.374865,1.192223,0.968403,0.433175
17,1.307264,1.283776,1.176005,1.098901,1.029920,1.351175,1.199064,0.993715,0.842470,0.715570,...,0.817013,0.623486,0.431088,0.691051,0.959677,1.243366,1.126979,0.944717,0.722863,0.352773
18,1.401166,1.272391,1.199282,1.154286,1.128571,1.298665,1.112820,0.932847,0.818660,0.741757,...,0.614286,0.406328,0.208003,0.843341,1.088811,1.018703,0.901020,0.717848,0.497545,0.429523
19,1.507803,1.631639,1.489196,1.374330,1.242200,1.735582,1.610425,1.393278,1.220572,1.057529,...,1.244170,1.036576,0.836416,0.293118,0.575876,1.632639,1.509291,1.314674,1.080155,0.705662
20,1.668740,1.175429,1.262792,1.350135,1.481588,1.020704,0.765720,0.805213,0.908576,1.040506,...,0.328882,0.545856,0.744092,1.777180,2.001020,0.371429,0.393052,0.485294,0.632778,1.067612
21,1.598469,1.134703,1.205189,1.280676,1.400073,1.000000,0.742857,0.749966,0.832993,0.951476,...,0.214286,0.434483,0.631163,1.664577,1.891172,0.402289,0.385979,0.428809,0.543045,0.958315
22,1.506787,1.114286,1.147683,1.195369,1.284920,1.022702,0.773146,0.714429,0.745736,0.825734,...,0.000000,0.225877,0.418208,1.451389,1.681229,0.506690,0.434483,0.371429,0.388613,0.772618
23,1.510845,1.204922,1.200014,1.215012,1.264911,1.153964,0.920182,0.810769,0.785714,0.810769,...,0.225877,0.000000,0.200510,1.231558,1.456863,0.627271,0.520008,0.368671,0.243277,0.658539
24,1.464129,1.242529,1.203427,1.188915,1.202463,1.229900,1.017400,0.868966,0.796933,0.771429,...,0.418208,0.200510,0.000000,1.033421,1.264669,0.812278,0.696639,0.520008,0.317194,0.536808
25,1.791419,1.923114,1.782280,1.666724,1.529572,2.021164,1.885768,1.673381,1.506246,1.348090,...,1.451389,1.231558,1.033421,0.000000,0.282843,1.786114,1.658682,1.458683,1.224412,0.991494
26,2.065509,2.205466,2.065072,1.948398,1.807016,2.300177,2.158467,1.949411,1.785714,1.630137,...,1.681229,1.456863,1.264669,0.282843,0.000000,1.971636,1.843079,1.642919,1.414935,1.271750
27,1.993305,1.535565,1.606731,1.676880,1.783828,1.390419,1.134343,1.152194,1.226660,1.327342,...,0.506690,0.627271,0.812278,1.786114,1.971636,0.000000,0.128571,0.328882,0.561703,1.267570
28,1.939598,1.513275,1.568436,1.626279,1.719338,1.385788,1.128662,1.120678,1.175429,1.259900,...,0.434483,0.520008,0.696639,1.658682,1.843079,0.128571,0.000000,0.200510,0.434483,1.171951
29,1.856978,1.485714,1.514431,1.551565,1.620909,1.388069,1.134703,1.085808,1.106659,1.162071,...,0.371429,0.368671,0.520008,1.458683,1.642919,0.328882,0.200510,0.000000,0.235606,1.026287
30,1.745490,1.446742,1.442996,1.454230,1.493523,1.386892,1.146156,1.050656,1.028671,1.045203,...,0.388613,0.243277,0.317194,1.224412,1.414935,0.561703,0.434483,0.235606,0.000000,0.850570
31,0.975203,0.939931,0.823774,0.748419,0.700583,1.030158,0.912945,0.690460,0.515079,0.365893,...,0.772618,0.658539,0.536808,0.991494,1.271750,1.267570,1.171951,1.026287,0.850570,0.000000

In [14]:
demandas_enteras = pd.DataFrame([5,7,8,8,7,4,6,7,8,8,7,1,7,7,5,5,6,0,4,1,8,7,5,5,5,4,1,6,6,6,5],index=distances_enteras.index,columns=['Demanda'])

In [15]:
demandas_enteras

    Demanda
1         5
2         7
3         8
4         8
5         7
6         4
7         6
8         7
9         8
10        8
11        7
12        1
13        7
14        7
15        5
16        5
17        6
18        0
19        4
20        1
21        8
22        7
23        5
24        5
25        5
26        4
27        1
28        6
29        6
30        6
31        5

In [16]:
costo_entero_horas = distances_enteras['18']*demandas_enteras['Demanda']/v *2 + demandas_enteras['Demanda']
costo_entero_horas.sum()

182.6795204385851

In [17]:
costo_entero_horas.sum()/24

7.611646684941046

In [40]:
(costo_entero_horas.sum()) + (parte_decimal_horas)

197.68062988673125

In [18]:
Costo_total_jornadas = (costo_entero_horas.sum()/8) + (parte_decimal_horas/8)
Costo_total_jornadas

24.710078735841407

# Agrupar rutas

In [32]:
# Crear una lista de cadenas donde cada cadena es la representación de una de las listas
rutas_str = [str(ruta) for ruta in rutas]

# Crear el DataFrame con una sola columna
df = pd.DataFrame(rutas_str, columns=['ruta'])

# Mostrar el DataFrame
print(df)

                              ruta
0       ['base', 1, 5, 11, 'base']
1        ['base', 6, 2, 8, 'base']
2   ['base', 7, 8, 14, 15, 'base']
3     ['base', 26, 25, 19, 'base']
4     ['base', 27, 28, 29, 'base']
5         ['base', 20, 22, 'base']
6         ['base', 13, 22, 'base']
7         ['base', 29, 30, 'base']
8         ['base', 11, 12, 'base']
9         ['base', 19, 16, 'base']
10    ['base', 22, 23, 24, 'base']
11    ['base', 12, 31, 15, 'base']
12        ['base', 30, 24, 'base']
13        ['base', 16, 17, 'base']
14            ['base', 15, 'base']

In [35]:
df.replace('[','').replace(']','',inplace=True)

In [39]:
rutas_str = [' '.join(map(str, ruta)) for ruta in rutas]

# Crear el DataFrame con una sola columna
df = pd.DataFrame(rutas_str, columns=['ruta'])

# Mostrar el DataFrame
df

                   ruta
0      base 1 5 11 base
1       base 6 2 8 base
2   base 7 8 14 15 base
3    base 26 25 19 base
4    base 27 28 29 base
5       base 20 22 base
6       base 13 22 base
7       base 29 30 base
8       base 11 12 base
9       base 19 16 base
10   base 22 23 24 base
11   base 12 31 15 base
12      base 30 24 base
13      base 16 17 base
14         base 15 base

In [38]:
df

                   ruta
0      base 1 5 11 base
1       base 6 2 8 base
2   base 7 8 14 15 base
3    base 26 25 19 base
4    base 27 28 29 base
5       base 20 22 base
6       base 13 22 base
7       base 29 30 base
8       base 11 12 base
9       base 19 16 base
10   base 22 23 24 base
11   base 12 31 15 base
12      base 30 24 base
13      base 16 17 base
14         base 15 base

In [27]:
#Convertir la lista de rutas en un DataFrame de una columna donde cada row sea una ruta y todas esten en una columna
pd.DataFrame(rutas,columns=['Rutas'])

ValueError: 1 columns passed, passed data had 6 columns

In [20]:
costos

[1.00011964149035,
 1.0001237184687999,
 1.000107121192535,
 1.0001001408785601,
 1.000093256117165,
 1.000077862553805,
 1.000074232989175,
 1.000060769662605,
 1.000065543732885,
 1.000055285365315,
 1.000052408291485,
 1.0000603974708748,
 1.000051137123305,
 1.00004746631106,
 1.00002046649826]

In [21]:
d

      Demanda
1        0.40
2        0.52
5        0.56
6        0.19
7        0.28
8        0.60
11       0.67
12       0.47
13       0.97
14       0.34
15       0.98
16       0.64
17       0.11
base     0.00
19       0.92
20       0.38
22       0.82
23       0.53
24       0.64
25       0.05
26       0.75
27       0.28
28       0.64
29       0.54
30       0.76
31       0.40

In [22]:
demandas_enteras['Demanda']

1     5
2     7
3     8
4     8
5     7
6     4
7     6
8     7
9     8
10    8
11    7
12    1
13    7
14    7
15    5
16    5
17    6
18    0
19    4
20    1
21    8
22    7
23    5
24    5
25    5
26    4
27    1
28    6
29    6
30    6
31    5
Name: Demanda, dtype: int64

In [23]:
distances_enteras['18']*(demandas_enteras['Demanda'])/v *2 + (demandas_enteras['Demanda'])

1     5.700583
2     7.890674
3     8.959426
4     8.923429
5     7.790000
6     4.519466
7     6.667692
8     7.652993
9     8.654928
10    8.593406
11    7.500000
12    1.059659
13    7.609262
14    7.389487
15    5.204665
16    5.237272
17    6.136121
18    0.000000
19    4.252465
20    1.094297
21    8.662857
22    7.430000
23    5.203164
24    5.104002
25    5.421671
26    4.435525
27    1.101870
28    6.540612
29    6.430709
30    6.298527
31    5.214761
dtype: float64